name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting with flake8
        run: flake8 .

      - name: Run notebook test
        run: |
          pip install nbconvert
          jupyter nbconvert --execute --to notebook --inplace multi_symbol_risk_dashboard.ipynb
