name: Run and Commit Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute multi_symbol_risk_dashboard.ipynb --output multi_symbol_risk_dashboard.ipynb

      - name: Commit and push executed notebook
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add multi_symbol_risk_dashboard.ipynb
          git diff --cached --quiet || git commit -m "Run notebook and update outputs"
          git push origin main
